api_token: "8195162287:AAGzrloKh76o_JZazF4VsIoJp-9onwLkjrg"
bot_username: "@Uploaderxs_01bot"
default_tag: "@ashianes"
admin_password: "iraj720"
delete_delay: 30
db_path: "files.db"
warning_text: "⚠️ فایل‌ها بعد از ۳۰ ثانیه حذف خواهند شد"
welcome_text: "سلام! برای دانلود روی لینک فایل کلیک کنید."
join_text: "لطفاً ابتدا در کانال‌های زیر عضو شوید:"
not_found_text: "فایل پیدا نشد یا لینک منقضی شده است."
sponsored_channels:
  - "@karina_edu"
  - "@tinoapp"
